# Generated by Django 4.2.16 on 2025-05-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0011_machine'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'myappLubd_userprofile'
          AND column_name = 'last_login_google'
    ) THEN
        ALTER TABLE "myappLubd_userprofile"
            ADD COLUMN "last_login_google" timestamp with time zone NULL;
    END IF;
END
$$;
                        """
                    ),
                    reverse_sql=(
                        """
ALTER TABLE "myappLubd_userprofile"
    DROP COLUMN IF EXISTS "last_login_google";
                        """
                    ),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='last_login_google',
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
        )
    ]
